### ISSUE TITLE
Program stucks while running pretrained model with no error message and no progress

### ISSUE THREAD

**Issue by itssubas** [danieljl/keras-image-captioning#10]
While running this script:``` python keras_image_captioning/inference.py --dataset-type test --method beam_search --beam-size 3 --training-dir results/flickr8k/final-model```

It outputs following and stucks with no further progress:

```
Using TensorFlow backend.
2018-07-28 08:03:38 | Loading hyperparams config..
2018-07-28 08:03:38 | Building model..
2018-07-28 13:48:44.074842: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-28 13:48:44.074885: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-28 13:48:44.074897: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-07-28 08:03:46 | Loading model weights..
2018-07-28 08:03:51 | Evaluating test set..
  0%|                                                    | 0/32 [00:00<?, ?it/s]
 ```

**Comment by rola93** [comment]
Hello @itssubas did you find any solution?

Thanks in advance!

**Comment by rola93** [comment]
Well finally I let it run all night long. The progress bar is completed with 970.02 seconds/iteration, with 32 iterations it is almost 9 hours.

However, there was an error while calculating the metrics. 

The following is a copy of the traceback. I didn't read it carefully to understand what is happening, so as soon as I do it, I'll open a proper issue.
```
$ python -m keras_image_captioning.inference --dataset-type test --method beam_search --beam-size 3 --training-dir results/flickr8k/final-model
Using TensorFlow backend.
2018-08-08 19:47:28 | Loading hyperparams config..
2018-08-08 19:47:28 | Building model..
2018-08-08 16:47:33.368409: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-08 16:47:33.368451: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-08 16:47:33.368460: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-08-08 19:47:35 | Loading model weights..
2018-08-08 19:47:38 | Evaluating test set..
100%|████████████████████████████████████████████████████████████| 32/32 [11:06:29<00:00, 970.02s/it]
Traceback (most recent call last):
  File "/home/rola93/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/rola93/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rola93/no_version/keras-image-captioning/keras_image_captioning/inference.py", line 312, in <module>
    fire.Fire(main)
  File "/home/rola93/.pyenv/versions/captioning_2/lib/python2.7/site-packages/fire/core.py", line 116, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/rola93/.pyenv/versions/captioning_2/lib/python2.7/site-packages/fire/core.py", line 330, in _Fire
    component, remaining_args)
  File "/home/rola93/.pyenv/versions/captioning_2/lib/python2.7/site-packages/fire/core.py", line 536, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/rola93/no_version/keras-image-captioning/keras_image_captioning/inference.py", line 293, in main
    include_prediction=True)
  File "/home/rola93/no_version/keras-image-captioning/keras_image_captioning/inference.py", line 57, in evaluate_test_set
    include_prediction=include_prediction)
  File "/home/rola93/no_version/keras-image-captioning/keras_image_captioning/inference.py", line 110, in _evaluate
    id_to_references)
  File "keras_image_captioning/metrics.py", line 61, in calculate
    id_to_references)
  File "keras_image_captioning/metrics.py", line 22, in calculate
    id_to_references, id_to_preds)
  File "pycocoevalcap/meteor/meteor.py", line 42, in compute_score
    scores.append(float(self.meteor_p.stdout.readline().strip()))
ValueError: could not convert string to float: 

```
(notice that the program doesn't seem to be terminated since there is not a new prompt in the terminal to keep typing new commands)

**Comment by itssubas** [comment]
@rola93 I guess my problem was because of different version of CUDA and CUDNN. I fixed it by installing CUDA 8.

**Comment by rola93** [comment]
Thanks for your answer! I'm running it with CPU only, perhaps with GPU is not that slow. I didn't have any time to open an issue for this other problem.

So if it is not an issue, this issue should be clossed.

Thanks
