### ISSUE TITLE
ValueError: Training label repro-final-model exists!

### ISSUE THREAD

**Issue by HankyuJang** [danieljl/keras-image-captioning#6]
When training the model, I get this ValueError.

```
(tensorflow2.7) [ec2-user@ip-172-31-14-61 keras-image-captioning]$ python -m keras_image_captioning.training   --training-label repro-final-model   --from-training-dir results/flickr8k/final-model
/home/ec2-user/anaconda2/envs/tensorflow2.7/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/envs/tensorflow2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ec2-user/anaconda2/envs/tensorflow2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ec2-user/keras-image-captioning/keras_image_captioning/training.py", line 283, in <module>
    fire.Fire(main)
  File "/home/ec2-user/anaconda2/envs/tensorflow2.7/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/ec2-user/anaconda2/envs/tensorflow2.7/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/ec2-user/anaconda2/envs/tensorflow2.7/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/ec2-user/keras-image-captioning/keras_image_captioning/training.py", line 262, in main
    training = checkpoint.training
  File "/home/ec2-user/keras-image-captioning/keras_image_captioning/training.py", line 247, in training
    explode_patience=sys.maxsize)
  File "/home/ec2-user/keras-image-captioning/keras_image_captioning/training.py", line 69, in __init__
    self._init_result_dir()
  File "/home/ec2-user/keras-image-captioning/keras_image_captioning/training.py", line 136, in _init_result_dir
    self._training_label))
ValueError: Training label repro-final-model exists!

```

**Comment by HankyuJang** [comment]
Thank you so much! It helped resolving the error I had previously :)
